for_training/for_training/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('oneapp.urls', namespace='oneapp')),
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
]

for_training/oneapp/urls.py
from django.urls import path

from . import views

app_name = 'oneapp'

urlpatterns = [
    #path('', views.DayAddView.as_view(), name='index'),
    path('', views.index, name='index'),
    #path('create/', views.day_create, name='day_create'),
    #path('ajax/', views.ajax, name='ajax'),
]

for_training/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeDoneView,
    PasswordChangeView, PasswordResetCompleteView,
    PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

for_training/templates/includes/error.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

for_training/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">I'</span>am</p>    
</footer>

for_training/templates/includes/form.html

{% comment %} <form method="post" class="form-horizontal" name="ourForm" action="{% url 'oneapp:index' %}">
  {% csrf_token %}
  <div class="form-group">
    <div class="day row">
      
        {% for field in day_form %}
          {% if field.name == 'pub_date' %}
            <div class="form-group col-md-3">
              <label for="{{ field.id_for_label }}" class="form-label">
                {{ field.label }}
              </label>
              <input type="date" class="form-control" name="Date" id="davaToday">
            </div>  
          {% else %}
            <div class="form-group col-md-2">
              <label for="{{ field.id_for_label }}" class="form-label">
                {{ field.label }}
              </label>
              {{field|addclass:'form-control'}}
            </div> 
          {% endif %}  
        {% endfor %}
         
    </div>   
    <hr> 
      <div class="exercises row" id="exercises">
        <h5>Упражнения</h5>
        

        <div class="input-group row justify-content-end">
          <div class="header-exercises form-group col-md-5">
            Мышечная группа
          </div> 
          <div class="header-exercises form-group col-md-6">
            Упражнение
          </div> 
        </div> 
        <div class="exercise" id="exercise">
          <div class="name-exercise input-group row">
            {% for field in exercise_form %}
              {% if field.name == 'exercise_number' %}
                <div class="exercise-number form-group col-md-1">
                  {{ field.value }}
                </div>
              {% elif field.name == 'name_exercise' %}
                <div class="form-group col-md-6">
                  {{ field|addclass:'form-select' }}
                </div> 
              {% else %}
                <div class="form-group col-md-5">
                  {{ field|addclass:'form-select' }}
                </div>  
              {% endif %}
            {% endfor %}
          </div> 
  
          <h6>Подходы</h6>
          <div class="sets">
            <div class="input-group row">
              <div class="form-group col-md-4">
                Вес
              </div> 
              <div class="form-group col-md-4">
                Повторения
              </div> 
            </div>  
            <div class="set input-group row">
              {% for field in set_form %}
                <div class="form-group col-md-4">
                  {{ field|addclass:'form-control form-control-sm' }}
                </div>  
              {% endfor %}
              <div class="form-group col-md-1">
                <input type="button" title="удалить подход" class="del_set btn btn-sm btn-success"/>
              </div>
            </div>
          </div>
          <input type="button" title="добавить подход" class="add_set btn btn-sm btn-success col-md-3" value="Добавить подход"/>
          <hr>
        </div>
      </div>
      <input type="button" id="add-exercise" title="добавить упражнение" class="btn btn-success col-md-3" value="Добавить упражнение"/>

    <hr>
    <div class="d-flex justify-content-end">
      <button type="submit" class="btn btn-primary">
        Сохранить 
      </button>
    </div>
  </div>  
</form> {% endcomment %}




{% comment %} <form method="post" class="form-horizontal" name="ourForm" action="{% url 'oneapp:index' %}">
  {% csrf_token %}
  {{ exercise_formset.management_form }}

  <div class="exercises row" id="exercises">
    <h5>Упражнения</h5>
    

    <div class="input-group row justify-content-end">
      <div class="header-exercises form-group col-md-5">
        Мышечная группа
      </div> 
      <div class="header-exercises form-group col-md-6">
        Упражнение
      </div> 
    </div> 
    
    <div class="exercise" id="exercise">
      {% for exercise in exercise_formset %}
        <div class="name-exercise input-group row">
          <div class="exercise-number form-group col-md-1">
            {{ forloop.counter }}
          </div>
          {% for field in exercise %} 
            {% if field.name == 'name_exercise' %}
              <div class="form-group col-md-6">
                {{ field|addclass:'form-select' }}
              </div> 
            {% else %}
              <div class="form-group col-md-5">
                {{ field|addclass:'form-select' }}
              </div>  
            {% endif %}
          {% endfor %}
        </div>
        <div>
          Подходы
        </div>
      {% endfor %}
    </div>
  </div>
  <input type="button" id="add-exercise" title="добавить упражнение" class="btn btn-success col-md-3" value="Добавить упражнение"/>
  <input type="submit" value="Submit">
</form> {% endcomment %}




<form id="form-container" method="post" action="{% url 'oneapp:index' %}">
  {% csrf_token %}

  {{ dayform }}

  {{ exerciseformset.management_form }}
  {% for form in exerciseformset.forms %}
    <div class="exercise-form">
      {{form.as_p}}
        {{ form.sets.management_form }}
        {% for nested_form in form.sets.forms %}
            {{ nested_form.as_div }}
        {% endfor %}
    </div>
  {% endfor %}
  <button class="btn btn-sm btn-secondary" id="add-exercise" type="submit">Добавить упражнение</button>
  <button class="btn btn-success" type="submit">Сохранить</button>
</form>

for_training/templates/includes/head.html
{% load static %}
<head>    
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
  <title>
    {% block title %} Последние обновления на сайте {% endblock %}
  </title>
</head>

for_training/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'oneapp:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Super</span>tren
      </a>
      {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills"> 
        {% if request.user.is_authenticated %}      
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" 
             href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>      
</header>